### ISSUE TITLE
Fix order of redirection events in index.js

### ISSUE THREAD

**Issue by sdnorris** [joelyjoel/singing-our-lives#39]
Repeated error on node server:
```
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/joel/singing-our-lives/node_modules/send/index.js:390:13)
    at SendStream.send (/home/joel/singing-our-lives/node_modules/send/index.js:617:10)
    at /home/joel/singing-our-lives/node_modules/send/index.js:774:12
    at FSReqWrap.oncomplete (fs.js:154:5)
```

**Comment by sdnorris** [comment]
https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client
